### ISSUE TITLE
Error Fly?

### ISSUE THREAD

**Issue by NycuRO** [Chalapa13/WorldGuard#30] opened 2017-11-08 20:46 UTC
![image](https://user-images.githubusercontent.com/13573011/32573413-98de974e-c4d6-11e7-87bf-450b4883ab01.png)

I'm exit from protection and fly works. Wtf? @Muqsit

**Comment by Muqsit** [comment] 2017-12-05 20:47
https://github.com/Muqsit/WorldGuard/commit/1b2c9922e1e4fd5682c1c3d702bbe58397e5a943

**Comment by Muqsit** [comment] 2017-12-06 18:17
The rewrite branch is still not suitable for production though, let this issue be open so no one else creates a duplicate of it

**Comment by NycuRO** [comment] 2017-12-07 16:12
Ok muqy 🗡

**Comment by awgybop1** [comment] 2019-09-11 01:04
Just checked and I had no problems. Make sure the value of "fly-mode" is set to "3", this will enable Flight while in the region and disable it when you leave.

**Closed by awgybop1** 2019-09-11 01:04 UTC
Labels: Rewritten
